### ISSUE TITLE
Delta tokens

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#1]
I just wanted to point out a couple of problems we've had in the past regarding delta tokens. 

The first version of deltabot had the delta symbol (**∆**) as a token, but it was somehow not recognising about half of the deltas in the subreddit. We found out this was because it scans the source text of a comment, which can be seen using the comment source feature in RES - [image](http://i.imgur.com/xbeYCUb.png). So we had to add &amp;#8710; as a token (I used amp; in between & and # to stop it becoming a symbol here, in case you're wondering), since we include it as a method of creating the symbol in our sidebar. 

This meant deltabot was picking up most of the deltas in the subreddit, but ocassionally it would still miss one. While we don't think it was the only reason for a delta being missed, we found out that some users were using an isoceles triangle symbol in place of a delta (I'm not sure how). These look very similar: ∆ and Δ. So this had to be added as a token as well. 

Hope this saves any confusion a second time round!

**Comment by MystK** [comment]
I've made the necessary changes and verified that it works in dad06a2.

**Comment by Snorrrlax** [comment]
Thanks! While &amp:#8710; is a necessary token, &amp;amp;#8710; shouldn't be included. This is confusing but basically if the amp; is included as part of the token, then when people are trying to demonstrate the unicode without it creating a delta symbol, a delta would be awarded. 

Basically the list should be this:

/&#8710;|∆|Δ|!delta/

**Comment by Snorrrlax** [comment]
I had to edit my comment because I screwed up the amp; bits. It makes sense now.

**Comment by MystK** [comment]
Hi @Snorrrlax, that was added because that is what the deltas get translated to. Please see below what DB3 looks at.

![image](https://cloud.githubusercontent.com/assets/7399140/13801249/643aa718-eaed-11e5-896e-bfe3f046187e.png)

How to reproduce

1. Make a comment in CMV with just `&#8710;`.
2. Go to `https://www.reddit.com/r/changemyview/comments.json` and observe that your comment shows up as the picture above in the `data.body` key.

**Comment by Snorrrlax** [comment]
Oh I see! Thanks for clearing that up

**Comment by Snorrrlax** [comment]
So if someone types &amp;amp;#8710; in a comment, which would show up as &amp;#8710; once the comment is submitted to perhaps explain unicode to a user, this wouldn't be awarded as a delta?

**Comment by MystK** [comment]
No, they would not be awarded a delta because it would show up as

![image](https://cloud.githubusercontent.com/assets/7399140/13801416/c997fdf8-eaee-11e5-8f88-13b896103054.png)

and

![image](https://cloud.githubusercontent.com/assets/7399140/13801421/cfe26914-eaee-11e5-9980-877bb17b10a1.png)


We should not tell people to type `&amp;#8710;` as it is not a delta, but `&#8710;` is a delta.

**Comment by Snorrrlax** [comment]
Awesome :)
