### ISSUE TITLE
Making DeltaBot troll-proof/spam-proof?

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#15]
It just occurred to me that DeltaBot could potentially be confused if a random user was to send it a random PM, or spam replies? Perhaps not, but I thought I'd check. We don't want DeltaBot trolls!

**Comment by MystK** [comment]
Anybody can send a PM with subject "add" and a permalink to the delta comment. It is not an issue because DB isn't actually just adding, it's verifying first, so it's not a problem. 

The feature isn't 100% yet (due to no support of edited/deleted comments), but after those are implemented, I don't think it would hurt to advertise the feature to CMV subscribers.

**Comment by Snorrrlax** [comment]
If someone started sending PMs to deltabot with no correct subject, would it crash?

**Comment by MystK** [comment]
No crashing. :)

**Comment by MystK** [comment]
Closed because it is troll/spam proof
