### ISSUE TITLE
Delete Command

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#16]
If someone misused the delta symbol, but included the right amount of characters for it to be approved like this:

"I agreed with you anyway, but I really think this is a great comment and you deserve a delta &#8710;"

Then DeltaBot would recognise it as a genuine delta and carry out the tasks as normal.

If this was brought to our attention, we'd have to manually reduce the flair count, remove it from the wiki page etc. 

Is it possible to introduce a delete command, which only the moderators can use, in the same form as the add command etc?

[Here](https://github.com/PixelOrange/MARS/issues/8) is the MARS issue of this.

The actions included:

* Delete/edit the DeltaBot confirmation comment and replace with "this comment was brought to the attention of the moderators as misuse/abuse of the delta, for x reason (customisable depending on command subject? delete1, delete2, delete3 etc?)
* Reduce user flair score
* Remove entry for delta history wiki page
* Reduce deltaboards (when applicable)
* Remove from /r/DeltaLog (when applicable) 
* Not yet confirmed: remove the delta comment (we might want to leave it up as an example of delta misuse for our readers)

**Comment by hacksoncode** [comment]
Unfortunately, since the new delta count mechanism is based on the wiki entries, and in particular on a hidden part that encodes the data that I'm terrified to touch, we currently have *no* effective way to remove a delta that was awarded in error (either for abuse, nor for accidental misawarding). 

I'd say that this change to the delta calculation increases the priority of this issue considerably.

**Comment by MystK** [comment]
Done. ;) Please message deltabot with the subject "delete" and the delta comment in the body, similar to add

**Comment by hacksoncode** [comment]
Woohoo! Thanks!

I haven't had to reboot the bot in more than a week, fwiw.

-- 
Ray
