### ISSUE TITLE
Something wrong with history updates

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#19]
My [history](https://www.reddit.com/r/changemyview/wiki/user/hacksoncode) has very recently become quite corrupted by the DB changes... not sure what's happened here, but it's pretty severe. 

The problem seems to have started today.

**Comment by hacksoncode** [comment]
This [diff](https://www.reddit.com/r/changemyview/wiki/user/hacksoncode?v=a3658ab2-31f0-11e6-8a1c-0e0110b1276d&v2=8994e7de-2ffe-11e6-8d65-0e8968835365) also shows that a bunch of stuff was corrupted internal to the existing delta history, such as usernames of people that gave me deltas being replaced by [deleted]... I think that stuff should be preserved as much as possible. 

This seems like a pretty urgent problem, as fixing it is just going to get more complicated the longer it festers.

**Comment by MystK** [comment]
Code has been pushed to resolve it. The [deleted] has to do with the first conversion of your delta history to the new format. The [deleted] usernames would have to be manually added back from the previous revision of your diff. From then on, your new deltas would never have [deleted].

There are still open issues about handling of deleted comments. Some of the [deleted] are due to deleted username, which would still be counted. Some are deleted comments, which I believe would not be counted. Deleted comments have been moved to #4 because they relate to that issue.

**Comment by MystK** [comment]
Also for some cool info, what you saw is the raw data DB3 uses to create the table.

![image](https://cloud.githubusercontent.com/assets/7399140/16032746/d2c2f27e-31bc-11e6-8d71-f87c083e1800.png)

It just looks garbled when seen on the wiki, but if you click edit, it looks clean.
