### ISSUE TITLE
Not all deltas in this post were added to DeltaLog

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#194]
This post: https://www.reddit.com/r/changemyview/comments/66eeci/cmv_vaccines_and_vaccinations_etc/

It has more than one delta from OP, but the /r/DeltaLog post for it only contains one.

**Comment by yleong** [comment]
Actually, 2 delta log posts were created for each recording down 1 delta.

https://www.reddit.com/r/DeltaLog/comments/66kj0y/deltas_awarded_in_cmv_vaccines_and_vaccinations/

https://www.reddit.com/r/DeltaLog/comments/66eltr/deltas_awarded_in_cmv_vaccines_and_vaccinations/

This is weird because [findOrMakeDeltaLogPost](https://github.com/MystK/delta-bot-three/blob/b8fec032075566c16f00d5f7c2c9889b411d92a9/src/index.js#L542) checks that there are no `possiblyExistingPost` before creating a delta log post

**Comment by MystK** [comment]
closing for now because this might have been fixed with the introduction of levelup db
