### ISSUE TITLE
DeltaBot keeps adding back deleted delta

### ISSUE THREAD

**Issue by whitef530** [MystK/delta-bot-three#213]
After sending a delete command, DeltaBot removes the delta, but adds it back later.

Post: https://www.reddit.com/r/changemyview/comments/7asfhb/cmv_i_think_the_sun_is_flat/dpcf2x8/

Modmail: https://mod.reddit.com/mail/all/29rtk

**Comment by MystK** [comment]
It’s because we have error checking which thinks it accidentally forgot to add a comment. There are multiple “check comment” bots I think lasting up to 30 minutes. To be safe, wait an hour and then send the command.

Antoine
________________________________

**Comment by hacksoncode** [comment]
Instead of deleting the metadata in the user's wiki page, could we just mark manually removed comments as manually removed so the bot doesn't reinsert them for any reason except an explicit "add" command?

A) It's a very significant usability headache for the mod wanting to remove a quickly reported delta to have a wait an hour (or even check each time, especially when they are doing it from the mod reports page). 

B) I don't think we can necessarily rely on the bot completing its action within an hour, since things sometimes seem to get flaky.

**Comment by hacksoncode** [comment]
Doh... stupid interface... sorry about the close and reopen.

**Comment by MystK** [comment]
Agreed the fix to this would be to mark delta comments that were deleted by a mod so the next queues know that it was not awarded on purpose.

**Comment by Snorrrlax** [comment]
I opened a new issue, so I'll close this one.
