### ISSUE TITLE
Double issued delta

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#28]
It seems to have gotten the count correct (which makes sense because there would be only 1 unique history entry), but DB issued two delta award comments to the same comment, here:

https://www.reddit.com/r/changemyview/comments/53gssm/cmv_freedom_of_religion_should_be/d7t97ec

and here:

https://www.reddit.com/r/changemyview/comments/53gssm/cmv_freedom_of_religion_should_be/d7t8vfl

**Comment by MystK** [comment]
This is due to DeltaBot not checking if DeltaBot has already commented on a comment when verifying if it is a valid delta or not.

This can be resolved by adding a check for children comments if DeltaBot has already commented in the "verifyThenAward" method.

This code to check if DeltaBot has already commented is already in the checkMessagesforDeltas method.

Snippet here

```
          const dbReply = _.reduce(_.get(replies, 'data.children'), (result, reply) => {
            if (result) return result
            else if (_.get(reply, 'data.author') === botUsername) return _.get(reply, 'data')
            return result
          }, null)
```

**Comment by MystK** [comment]
Hey @roastchicken , this is related to the double message.

Basically we need to check before retrying.
see #14 quote below

> Yes. The root cause is in our Reddit API file. If the response does not return us a good number (Status Code 200), retry.
> 
> In order to fix this. We would have to add a callback into the RedditAPI driver.
> 
> “Send a PM. If Reddit gives us an error, wait 30 seconds, check if the PM we wanted to send was sent. If good, continue, else, retry”
> “Write a comment. If Reddit gives us an error, wait 30 seconds, check if the comment we wanted to write was written. If good, continue, else, retry”

CC @roastchicken @Snorrrlax

**Comment by sxlijin** [comment]
Does this mean that on top of duplicating the `dbReply` check from `checkMessagesForDelta` in `verifyForAward`, `reddit-api-driver` needs to be updated to re-poll Reddit itself?

**Comment by MystK** [comment]
You may be correct @sxlijin depending on if we have the comment reply data or not on dbReply check. I haven't looked at that snippet recently, so I am not positive.

**Comment by sxlijin** [comment]
Is that because of a post-comment-check-comment race condition?

I haven't dug through the code itself yet (I have a lot of other things going on, just saw @Snorrrlax's cry for help in the sub and figured I'd take a look), but I imagine the model itself (`POST` to Reddit to add a comment, `GET` to check if the comment exists) can cause problems there.

**Comment by Snorrrlax** [comment]
@sxlijin Can I 'assign' you to this? (i.e. I'd add the 'in progress' label since I can't actually assign)
