### ISSUE TITLE
Deltaboard Formatting

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#31]
Low priority, but at some point can we change all the deltaboard layouts to this:

| Rank | Username | Deltas |
| :------: | :------: | :------: |
| 1 | **garnteller** ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 9 |
| 2 | Ansuz07 ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 9 |
| 3 | cacheflow ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 7 |
| 4 | srnkmrsn ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 6 |
| 5 | Gladix ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller"garnteller's delta history wiki page" )) | 5 |
| 6 | Amablue ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 7 | cdb03b ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 8 | PreacherJudge ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 9 | Grunt08 ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 4 |
| 10 | Generic_On_Reddit ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 4 |
| |As of 9/25/16 15:36 EDT| |
| |[More Deltaboards](http://www.reddit.com/r/changemyview/wiki/deltaboards)| |

To sum up the changes here, we'll include a wiki link in brackets with their total delta score - which when hovered over says "username's delta history wiki page" (I just copied and pasted garnteller's one here)

Thanks!

**Comment by MystK** [comment]
Yes. Can you please make that a separate issue so I can track it easier?

Get Outlook for iOS




On Tue, Sep 27, 2016 at 12:23 PM -0700, "Snorrrlax" <notifications@github.com> wrote:





Low priority, but at some point can we change all the deltaboard layouts to this:

| Rank | Username | Deltas |
| :------: | :------: | :------: |
| 1 | **garnteller** ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 9 |
| 2 | Ansuz07 ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 9 |
| 3 | cacheflow ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 7 |
| 4 | srnkmrsn ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 6 |
| 5 | Gladix ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller"garnteller's delta history wiki page" )) | 5 |
| 6 | Amablue ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 7 | cdb03b ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 8 | PreacherJudge ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 5 |
| 9 | Grunt08 ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 4 |
| 10 | Generic_On_Reddit ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")) | 4 |
| |As of 9/25/16 15:36 EDT| |
| |[More Deltaboards](http://www.reddit.com/r/changemyview/wiki/deltaboards)| |

To sum up the changes here, we drop the **/u/** from the usernames, include a wiki link in brackets with their total delta score - which when hovered over says "username's delta history wiki page" (I just copied and pasted garnteller's one here), and drop the delta symbol and link from the third column.

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/MystK/delta-bot-three/issues/31

**Comment by Snorrrlax** [comment]
This is a separate issue?

**Comment by MystK** [comment]
thanks ;) was on my phone and didn't see

**Comment by Snorrrlax** [comment]
Apologies if anybody started working on this issue - but we're going to put it on pause. I think some of us mods might actually prefer the Deltaboard format we currently have. I'll report back soon if we're still going with this or not.

**Comment by Snorrrlax** [comment]
Okay I can safely confirm this issue is no longer necessary as we'd like to stick with our current format. Apologies again.

Closing issue.
