### ISSUE TITLE
/u/garnteller's wiki page

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#58]
Does anyone know why garnteller's [wiki page](https://www.reddit.com/r/changemyview/wiki/user/garnteller) is different to (as far as I can see) everyone else's? ([Example](https://www.reddit.com/r/changemyview/wiki/user/convoces)).

/u/garnteller's sprawls off the edge.

This might be a CSS bug, but thought I'd check.

**Comment by hacksoncode** [comment]
Could you clarify what you think is different between them? Viewed in Firefox on my desktop monitor they look nearly identical in formatting.

**Comment by Snorrrlax** [comment]
Garnteller: [image](http://imgur.com/VQGHCSL)

Convoces: [image](http://imgur.com/QT7jVzi)

**Comment by Snorrrlax** [comment]
It's clearer when on mobile:

[One](http://imgur.com/9MXernR) and [two](http://imgur.com/LtsIAhQ).

**Comment by hacksoncode** [comment]
I have a theory. One of garnteller's awards is for a thread with the title "CMV: Single Moms don't deserve sympathy as most of their bills are paid by government &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; social programs"

That big pile of "amp"'s being repeated acts like a single really long word, so there's no way for the table code to autowrap it on smaller displays. The actual post only has a single ampersand in the title. 

I think this is an artifact of one of the bugs that cropped up in DB2 (?) where ampersands sometimes got repeatedly multiplied in weird ways. 

Probably the only way to fix this would be to scrub the wiki entries to fix those problems... but that's yet another script that someone would have to write to do that's automatically... because I'm certainly not going to volunteer to do it manually. 

There might be something that could be done in the CSS to clip any words that are too long.

**Comment by Snorrrlax** [comment]
Thoughts on this @MystK?

**Comment by MystK** [comment]
@hacksoncode is the winner! I removed the ;amp and everything looks good.

**Comment by Snorrrlax** [comment]
This might be a widespread issue though?

**Comment by Snorrrlax** [comment]
I said garnteller's was different to everyone else's, but I shouldn't have, since I've not looked through that many pages!

**Comment by MystK** [comment]
Yes good point. You're probably right that this is a widespread issue. I'm pretty confident I know what we need to do to fix this. We have to use a HTML encode and decoder and make sure it gets parses through the wiki data before we touch it. I guess we'll leave this up. ;)

**Comment by hacksoncode** [comment]
It's probably limited to whoever received a delta during a relatively brief
period when one of the previous bots had a bug that mysteriously repeatedly
amplified amp; symbols... but unfortunately I don't know how to determine
who those people might have been.

**Comment by MystK** [comment]
Is this still an issue? I don't see it happening anymore.

https://www.reddit.com/r/changemyview/wiki/user/garnteller

**Comment by Snorrrlax** [comment]
The problem is we don't really know if it's still an issue anymore, since to be sure we'd have to check every wiki page. I reckon there's probably one or two out there, but I'm happy to deal with this on a case by case basis if that's easier for you (and if any cases even exist).

**Comment by MystK** [comment]
Yes, it's most likely impossible to handle by computer. I'd like to address it case by case. Will close this for now.

**Comment by Snorrrlax** [comment]
Found another one: https://www.reddit.com/r/changemyview/wiki/user/crayshack

I think it's happening when there's a & in the post title.
