### ISSUE TITLE
Maybe check out HyperDev.com?

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#77]
I realize that github issues probably aren't the best place to talk about ideas like this, but I'm not sure anyone still looks at /r/DeltaBotV3...

I was just catching up on long overdue RSS feeds, and I noticed [this Joel Spolsky blog entry](http://www.joelonsoftware.com/items/2016/05/30.html) about hyperdev.com. 

It seems like it could be an interesting development platform for DB3, since it's basically a free WYSIWYG instant-deployment Node server... Maybe even get rid of the VM and use it for production...

**Comment by MystK** [comment]
I checked it out before and I think it's a min playground to prototype stuff very quickly. It's pretty cool and might help others be able to set up their development environments quickly, but I don't think it's a replacement for a live production server. If we close the browser, the whole thing stops.

Also since we're talking about playgrounds and IDEs, c9.io is also a pretty good alternative/addition to hyperdev. It's like HyperDev except more permanent.
