### ISSUE TITLE
Underscores in username creating bold/italics

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#79]
Currently on the daily deltaboard there is a user who's name is /u/___ OccamsChainsaw ___ which appears [like this](http://i.imgur.com/mTLpArY.jpg). Reddit recognises underscores in the same way as asterisks - bold, italics, or in this case bold *and* italics (3 underscores on each side). 

Is there a way we can stop this from happening on deltaboards?

**Comment by hacksoncode** [comment]
At first when I tried to go to that userpage, I hadn't seen the underscores, because they disappeared in the email version of the above comment... but interestingly there actually also is a user called OccamsChainsaw *without* the underscores. Chaos, confusion, discord, bureaucracy, and international relations!!!!

Anyway, the obvious solution would be to prepend all underscores in display text with "\" to quote them... but I'm not sure how *that* would work either.

**Comment by MystK** [comment]
Yes. Should be fairly straightforward to append username underscores with /

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Nov 2, 2016 at 7:40 AM -0700, "hacksoncode" <notifications@github.com<mailto:notifications@github.com>> wrote:


At first when I tried to go to that userpage, I hadn't seen the underscores, because they disappeared in the email version of the above comment... but interestingly there actually also is a user called OccamsChainsaw without the underscores. Chaos, confusion, discord, bureaucracy, and international relations!!!!

Anyway, the obvious solution would be to prepend all underscores in display text with "\" to quote them... but I'm not sure how that would work either.

-

**Comment by MystK** [comment]
PR from @wyantb merged. Pending approval and testing from @Snorrrlax on changemyviewdb3dev
