### ISSUE TITLE
Deltaboard Wiki Page Update (Multiple Timestamps)

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#85]
Again, low priority. Currently there is only one timestamp at the bottom of the [deltaboards wiki](https://www.reddit.com/r/changemyview/wiki/deltaboards), but it'd be nice if each table had their own one, since the time between updating will vary greatly between each board. 

I think the format should be the same as the sidebar deltaboard (i.e. a row at the bottom of the table).

**Comment by MystK** [comment]
This is slight more complicated than easy because the whole Wiki page gets updated on any single change, and there is no saved data of last updated that DB3 can read.

We would need to store the last parsed date as a hidden param per wiki board, and use the new parsed date ONLY if it has been updated.
