### ISSUE TITLE
Yearly Deltaboard (Update) 

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#96]
With 2017 quickly approaching us, it seems like launching the yearly deltaboard (#36) on New Year's Day would make sense. No back tracking of deltas would be required to populate the deltaboard; it would start afresh. 

I'd quite like to bump up the priority of the yearly deltaboard to make this happen. What do you think?

**Comment by MystK** [comment]
Yes, not having to track non DB3 comments would alleviate the issue, but if I remember correctly, I don't think I know of a systematic way yet to grab all awarded deltas. for the year, due to the issue that DeltaBot's comments only go back about a month.

At the moment, the only solution I can think of, is to scrap all of the wiki delta history to compile a yearly board, perhaps every week. 

Did you want to prioritize this over edit?

**Comment by Snorrrlax** [comment]
Would the Historical Monthly Deltaboards feature (#92) help with this? 

I'd like to priortise this over edit if launching the yearly deltaboard on new year's day makes it easier for you.

**Comment by MystK** [comment]
From development perspective, if we go with my suggested approach above, when we launch it makes no difference in level of difficulty. #92 would benefit from the development of this, and I'd be able to backtrack from the user history delta history boards.

**Comment by Snorrrlax** [comment]
Would it make sense to do #92 before a yearly deltaboard then? If starting on new year's day doesn't make the deltaboard more accurate/easier to implement for you, then edit should remain a priority.

**Comment by hacksoncode** [comment]
Isn't the idea to just update the board dynamically? Why is there a need to look at *any* history?

Every time a delta is awarded, just increment and keep track of the user's yearly total so far in a hidden field on their wiki page. If the user's previous wiki entry was from last year, reset their count to 1. 

If incrementing the stored annual delta count bumps someone's position on the board, bump them, otherwise leave it alone. 

If it's done that way, then yes, it would save a *lot* of effort to start at the new year, because otherwise you really *would* have to scrape everyone's wiki for all deltas to date in the year in order to have an accurate count. 

It would save considerable processing time to do it that way for all 3 deltaboards, actually. Do you really scrape the entire month's history now on every delta?

**Comment by MystK** [comment]
Yes, updating the yearly delta board after a delta is awarded is one solution. My main concern with that is it introduces permanent bugs/issues if something goes wrong during the delta awarding.

For monthly boards at the moment, we scrape Deltabot's comments to compile the boards up to monthly.

My thought was to scrape the whole wiki once every week to compile the yearly delta boards, but I'm not sure if it's the best solution.

If we decide to update yearly delta board on delta award, we'll still have about a month to implement that solution after the start of 2017.

**Comment by hacksoncode** [comment]
Yeah, ok, that would work. As long as we test scraping back an entire year's worth of wiki entries when we implement it, that's probably ok. 

I guess if we're even just reasonably careful we can avoid having the bot run the server out of memory when doing a full-year scrape. 

Depends on how long it takes for a year's data, I suppose... if it's long enough that it could interfere with DB's regular activities, maybe it could be a separate cron job or something.

**Comment by TheJaySmith** [comment]
Do we have a staging area for the code?

**Comment by roastchicken** [comment]
@TheJaySmith if by staging area you mean a bot run for development purposes, then no, I don't believe so. The suggested way to test is to run the bot on your own computer using a bot account you create on a testing subreddit you make.

**Comment by TheJaySmith** [comment]
Perfect. Was just curious. I have been playing with reddit's code and may be able to make a staging area out of it. Let me play with this a little more.

**Comment by Snorrrlax** [comment]
@TheJaySmith any update on a staging area?

**Comment by Snorrrlax** [comment]
@MystK what is your preferred approach for this? Above you mention that we have the first month of 2017 to achieve one approach, so we should probably decide soon.

**Comment by MystK** [comment]
I'd like to somehow scrape deltabot's comments for the year. I think this is the best, most accurate approach.

**Comment by RaoulMeyer** [comment]
I built a way to store delta counts per user in such a way that it is easy to then determine the top ten users for a year. It fetches the most recent deltabot comments and stores the deltas each user received each day in a separate file (So one file for every day of the year).

Publishing this info to the wiki still has to be added, but this should be relatively easy as a function that returns the top ten users of a year already exists.

Because the deltas are saved as JSON files, I think this might also make it a lot easier to create the all-time boards (#34) after all comments are scanned (#119). 

@MystK do you agree with the way this is set up? Any feedback is welcome.

**Comment by MystK** [comment]
Hi @RaoulMeyer, I think the best approach would be a "stateless" approach, but I am not sure how viable that would be. This is an open source project so all contributions are welcome. A PR would be greatly appreciated. :)
